DoAn_21806064393/Controllers/EmployerController.cs
using DoAn_21806064393.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using System.IO;
using System.Security.Cryptography;
using System.Text;

namespace DoAn_21806064393.Controllers
{
    public class EmployerController : Controller
    {
        // GET: Employer
        DataClasses1DataContext data = new DataClasses1DataContext();
        public ActionResult userNV(int? page)
        {
            if (Session["LoggedInUser"] != null && (int)Session["UserRole"] == 3)
            {
                if (page == null) page = 1;
                var all_user = (from s in data.Users select s).OrderByDescending(m => m.id_user);
                int pageSize = 8;
                int pageNum = page ?? 1;
                return View(all_user.ToPagedList(pageNum, pageSize));
            }
            else
            {
                return RedirectToAction("Login", "User");
            }
        }
        [HttpPost]
        public ActionResult LockUser(int id)
        {
            var user = data.Users.FirstOrDefault(u => u.id_user == id);
            if (user != null)
            {
                if (user.roles == 1 )
                {
                    // Trả về thông báo lỗi khi không thể khóa tài khoản của sếp
                    return Json(new { success = false, message = "Giỡn Mặt Hả Dám Khóa Tài Khoản Sếp" });
                }
                else
                {
                    user.status = 1;
                    data.SubmitChanges();
                    return Json(new { success = true });
                }
            }
            else
            {
                return Json(new { success = false, message = "Không tìm thấy người dùng." });
            }
        }
        [HttpPost]
        public ActionResult UnlockUser(int id)
        {
            var user = data.Users.FirstOrDefault(u => u.id_user == id);
            if (user != null)
            {
                user.status = 0;
                data.SubmitChanges();
                return Json(new { success = true });
            }
            else
            {
                return Json(new { success = false });
            }
        }
        [HttpPost]
        public ActionResult ChangePassword(int id, string newPassword)
        {
            try
            {
                // Truy vấn cơ sở dữ liệu để tìm người dùng cần thay đổi mật khẩu
                var user = data.Users.FirstOrDefault(u => u.id_user == id);

                // Kiểm tra xem người dùng có tồn tại không
                if (user != null)
                {
                    // Cập nhật mật khẩu mới
                    user.password = AESEncryption.Encrypt(newPassword);

                    // Lưu thay đổi vào cơ sở dữ liệu
                    data.SubmitChanges();

                    // Trả về kết quả thành công
                    return Json(new { success = true });
                }
                else
                {
                    // Trả về kết quả thất bại nếu không tìm thấy người dùng
                    return Json(new { success = false, message = "Người dùng không tồn tại." });
                }
            }
            catch (Exception ex)
            {
                // Xử lý lỗi và trả về kết quả thất bại
                return Json(new { success = false, message = ex.Message });
            }
        }
        public static class AESEncryption
        {
            private const string EncryptionKey = "yourEncryptionKey";

            public static string Encrypt(string plainText)
            {
                byte[] clearBytes = Encoding.Unicode.GetBytes(plainText);
                using (Aes encryptor = Aes.Create())
                {
                    Rfc2898DeriveBytes pdb = new Rfc2898DeriveBytes(EncryptionKey, new byte[] { 0x49, 0x76, 0x61, 0x6E, 0x20, 0x4D, 0x65, 0x64, 0x76, 0x65, 0x64, 0x65, 0x76 });
                    encryptor.Key = pdb.GetBytes(32);
                    encryptor.IV = pdb.GetBytes(16);
                    using (MemoryStream ms = new MemoryStream())
                    {
                        using (CryptoStream cs = new CryptoStream(ms, encryptor.CreateEncryptor(), CryptoStreamMode.Write))
                        {
                            cs.Write(clearBytes, 0, clearBytes.Length);
                            cs.Close();
                        }
                        plainText = Convert.ToBase64String(ms.ToArray());
                    }
                }
                return plainText;
            }

            public static string Decrypt(string cipherText)
            {
                cipherText = cipherText.Replace(" ", "+");
                byte[] cipherBytes = Convert.FromBase64String(cipherText);
                using (Aes encryptor = Aes.Create())
                {
                    Rfc2898DeriveBytes pdb = new Rfc2898DeriveBytes(EncryptionKey, new byte[] { 0x49, 0x76, 0x61, 0x6E, 0x20, 0x4D, 0x65, 0x64, 0x76, 0x65, 0x64, 0x65, 0x76 });
                    encryptor.Key = pdb.GetBytes(32);
                    encryptor.IV = pdb.GetBytes(16);
                    using (MemoryStream ms = new MemoryStream())
                    {
                        using (CryptoStream cs = new CryptoStream(ms, encryptor.CreateDecryptor(), CryptoStreamMode.Write))
                        {
                            cs.Write(cipherBytes, 0, cipherBytes.Length);
                            cs.Close();
                        }
                        cipherText = Encoding.Unicode.GetString(ms.ToArray());
                    }
                }
                return cipherText;
            }
        }

    }
}

DoAn_21806064393/Controllers/collaboratorsController.cs
using DoAn_21806064393.Models;
using System;
using PagedList;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DoAn_21806064393.Controllers
{
    public class collaboratorsController : Controller
    {
        // GET: collaborators
        DataClasses1DataContext data = new DataClasses1DataContext();
        public ActionResult listaccCTV(int? page)
        {
            if (Session["LoggedInUser"] != null && (int)Session["UserRole"] == 2)
            {
                if (page == null) page = 1;
                var all_acc = (from s in data.accs select s).OrderByDescending(m => m.id_acc);
                int pageSize = 8;
                int pageNum = page ?? 1;
                return View(all_acc.ToPagedList(pageNum, pageSize));
            }
            else
            {
                return RedirectToAction("Login", "User");
            }
        }
        public ActionResult EditListCTV(int id)
        {
            var E_acc = data.accs.First(m => m.id_acc == id);
            return View(E_acc);
        }

        [HttpPost]
        public ActionResult EditListCTV(FormCollection collection, int id)
        {

            var s = data.accs.First(m => m.id_acc == id);
            var name = collection["account"];
            var pass = collection["password"];
            var maumat = Convert.ToInt32(collection["so_mau_mat"]);
            var tuong = Convert.ToInt32(collection["so_tuong"]);
            var skin = Convert.ToInt32(collection["so_skin"]);
            var tatus = collection["status"];
            var price = Convert.ToDecimal(collection["gia"]);
            var hinh = collection["imageURL"];
            s.id_acc = id;
            if (string.IsNullOrEmpty(name))
            {
                ViewData["Error"] = "Don't empty!";
            }
            else
            {
                s.account = name.ToString();
                s.password = pass.ToString();
                s.so_mau_mat = maumat;
                s.so_tuong = tuong;
                s.so_skin = skin;
                s.status = tatus.ToString();
                s.gia = price;
                s.imageURL = hinh;
                data.SubmitChanges();
                TempData["SuccessThemAcc"] = "Đã Sửa Acc Thành Công!";
                return RedirectToAction("listaccCTV");
            }
            return this.EditListCTV(id);
        }
        public ActionResult CreateListCTV()
        {
            if (Session["LoggedInUser"] != null && (int)Session["UserRole"] == 2)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Login", "User");
            }
        }
        [HttpPost]
        public ActionResult CreateListCTV(FormCollection collection, acc s, HttpPostedFileBase file)
        {
            if (Session["LoggedInUser"] != null && (int)Session["UserRole"] == 2)
            {
                var name = collection["account"];
                var pass = collection["password"];
                var maumat = Convert.ToInt16(collection["so_mau_mat"]);
                var tuong = Convert.ToInt16(collection["so_tuong"]);
                var skin = Convert.ToInt16(collection["so_skin"]);
                var price = Convert.ToDecimal(collection["gia"]);
                var hinh = collection["imageURL"];

                if (string.IsNullOrEmpty(name))
                {
                    ViewData["Error"] = "Don't empty!";
                }
                else
                {
                    s.account = name.ToString();
                    s.password = pass.ToString();
                    s.so_mau_mat = maumat;
                    s.so_tuong = tuong;
                    s.so_skin = skin;

                    // Lấy giá trị khuyến mãi từ form collection
                    var khuyenMaiPercent = Convert.ToDecimal(collection["khuyenmai"]);

                    // Kiểm tra giá trị khuyến mãi và tính toán giá sau khi khuyến mãi
                    decimal giaSauKhuyenMai = price;
                    if (khuyenMaiPercent > 0)
                    {

                        giaSauKhuyenMai = price * (1 - khuyenMaiPercent / 100);
                    }

                    s.gia = giaSauKhuyenMai;
                    s.giasaukhuyenmai = giaSauKhuyenMai;
                    s.imageURL = hinh;
                    s.status = "da up";
                    data.accs.InsertOnSubmit(s);
                    data.SubmitChanges();
                    TempData["SuccessThemAcc"] = "Đã Thêm Acc Thành Công!";
                    return RedirectToAction("listaccCTV");
                }
                return this.CreateListCTV();
            }
            else
            {
                return RedirectToAction("Login", "User"); 
            }
        }

    }
}

DoAn_21806064393/Views/Shared/LayoutCTV.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Trang Cộng Tác Viên</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        .admin-menu {
            background-color: #333;
            color: #fff;
            height: 100vh;
        }

            .admin-menu a {
                display: block;
                padding: 10px;
                color: #fff;
                text-decoration: none;
            }

                .admin-menu a:hover {
                    background-color: #555;
                }

        .admin-content {
            padding: 20px;
        }
    </style>
</head>

<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-2 admin-menu">
                <h4>Admin Panel</h4>
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link" href="#">Xin Chào @Session["UserName"]</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("listaccCTV", "collaborators")">Quản lý tài khoản game</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Logout", "Admin")">Đăng xuất</a>
                    </li>
                </ul>
            </div>
            <div class="col-md-10 admin-content">
                @RenderBody()
                @RenderSection("upload", required: false)
            </div>
        </div>
    </div>
</body>


</html>

DoAn_21806064393/Views/Shared/LayoutNhanVien.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Trang Nhân Viên</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://kit.fontawesome.com/1f9baf8be7.js" crossorigin="anonymous"></script>
    <style>
        .admin-menu {
            background-color: #333;
            color: #fff;
            height: 100vh;
        }

            .admin-menu a {
                display: block;
                padding: 10px;
                color: #fff;
                text-decoration: none;
            }

                .admin-menu a:hover {
                    background-color: #555;
                }

        .admin-content {
            padding: 20px;
        }
    </style>
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-2 admin-menu">
                <h4>Admin Panel</h4>
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link" href="#">Xin Chào @Session["UserName"]</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("userNV", "Employer")">Quản Lý Khách Hàng</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Logout", "Admin")">Đăng xuất</a>
                    </li>
                </ul>
            </div>
            <div class="col-md-10 admin-content">
                @RenderBody()
                @RenderSection("upload", required: false)
            </div>
        </div>
    </div>
</body>
</html>

DoAn_21806064393/Views/Shared/_LayoutAdmin.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Admin</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://kit.fontawesome.com/1f9baf8be7.js" crossorigin="anonymous"></script>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 16px;
        }

        .admin-menu {
            background-color: #343a40; /* Màu nền tối */
            color: #fff; /* Màu chữ trắng */
            min-height: 100vh;
            overflow-y: auto;
        }

            .admin-menu a {
                display: block;
                padding: 10px;
                color: #fff;
                text-decoration: none;
            }

                .admin-menu a:hover {
                    background-color: #495057;
                }

        .admin-content {
            padding: 20px;
            background-color: #f8f9fa;
            color: #212529;
        }

        .admin-menu h4 {
            font-size: 1.25rem;
        }

        .admin-menu a {
            font-size: 1rem;
        }
        .nav-header {
            margin-top: 20px;
        }
        .rounded {
            border-radius: 10px;
        }

    </style>
    @RenderSection("myCustomScripts", required: false)
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-2 admin-menu">
                <h4 class="text-center mt-3 mb-4">Admin Panel</h4>
                <ul class="nav flex-column">
                    <li class="nav-item has-treeview menu-open">
                        <a href="@Url.Action("doanhthu", "Admin")" class="nav-link active d-flex align-items-center bg-primary rounded">
                            <i class="nav-icon fas fa-tachometer-alt mr-2 text-white"></i>
                            <p class="mb-0 text-white">
                                Dashboard
                            </p>
                        </a>
                    </li>
                    <li class="nav-header">THỐNG KÊ</li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("ThongKe", "Admin")">
                            <i class="fas fa-history"></i> Tài Khoản Đã Bán
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("BalanceHistory", "Admin")">
                            <i class="fas fa-money-bill-wave"></i> Biến Động Số Dư
                        </a>
                    </li>
                    <li class="nav-header">QUẢN LÝ</li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index", "Admin")">
                            <i class="fas fa-users"></i> Quản Lý Thành Viên
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("listacc", "Admin")">
                            <i class="fas fa-gamepad"></i> Quản Lý Tài Khoản Game
                        </a>
                    </li>
                    <li class="nav-header">CÀI ĐẶT </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Logout", "Admin")">
                            <i class="fas fa-sign-out-alt"></i> Đăng Xuất
                        </a>
                    </li>
                </ul>
            </div>
            <div class="col-md-10 admin-content">
                @RenderBody()
                @RenderSection("upload", required: false)
            </div>
        </div>
    </div>
</body>
</html>